import 'package:flutter/material.dart';

/// Represents a product from the FogShield Price List JAN 2026.
class Product {
  final String sNo;
  final String model;
  final String name;
  final String description;
  final String warranty;
  final double endUserPrice;
  final double mrp;
  final String imagePath;
  final String coverage;
  final String category;

  const Product({
    required this.sNo,
    required this.model,
    required this.name,
    required this.description,
    required this.warranty,
    required this.endUserPrice,
    required this.mrp,
    required this.imagePath,
    required this.coverage,
    required this.category,
  });

  String get formattedPrice => '₹${endUserPrice.toStringAsFixed(0)}';
  String get formattedMrp => '₹${mrp.toStringAsFixed(0)}';
}

/// THE COMPLETE JAN 2026 PRICE LIST (All 26 Entries)
final List<Product> fogShieldProducts = [
  // --- FOGSHIELD PRO SERIES (IP + 4G) ---
  const Product(
    sNo: '1',
    model: 'SEC FSG1A MG4I',
    name: 'FogSHIELD Pro 4,590 ft³',
    description: 'IOT Fogging System Fog Generator. Suitable for fogging up to appx 4590 cubic feet volume with less than 1m visibility. Inbuilt multi-communication channel GSM, 4G & IP',
    warranty: '1',
    endUserPrice: 100800,
    mrp: 118908,
    imagePath: 'assets/product/foggshield_image_1.png',
    coverage: '4,590 ft³',
    category: 'PRO',
  ),
  const Product(
    sNo: '2',
    model: 'SEC FSG1B MG4I',
    name: 'FogSHIELD Pro 7000 ft³',
    description: 'IOT Fogging System Fog Generator. Suitable for fogging up to appx 7000 cubic feet volume with less than 1m visibility. Inbuilt multi-communication channel GSM, 4G & IP',
    warranty: '1',
    endUserPrice: 119872,
    mrp: 141449,
    imagePath: 'assets/product/foggshield_image_1.png',
    coverage: '7,000 ft³',
    category: 'PRO',
  ),
  const Product(
    sNo: '3',
    model: 'SEC FSG1E MG4I',
    name: 'FogSHIELD Pro 17500 ft³',
    description: 'IOT Fogging System Fog Generator. Suitable for fogging up to appx 17500 cubic feet volume with less than 1m visibility. Inbuilt multi-communication channel GSM, 4G & IP',
    warranty: '1',
    endUserPrice: 165641,
    mrp: 195456,
    imagePath: 'assets/product/foggshield_image_1.png',
    coverage: '17,500 ft³',
    category: 'PRO',
  ),
  const Product(
    sNo: '4',
    model: 'SEC FSG1H MG4I',
    name: 'FogSHIELD Pro 28000 ft³',
    description: 'IOT Fogging System Fog Generator. Suitable for fogging up to appx 28000 cubic feet volume with less than 1m visibility. Inbuilt multi-communication channel GSM, 4G & IP',
    warranty: '1',
    endUserPrice: 191667,
    mrp: 226167,
    imagePath: 'assets/product/foggshield_image_1.png',
    coverage: '28,000 ft³',
    category: 'PRO',
  ),

  // --- FOGSHIELD PRO SERIES (GSM + 4G) ---
  const Product(
    sNo: '5',
    model: 'SEC FSG1A MG4',
    name: 'FogSHIELD Pro 4,590 ft³ (4G)',
    description: 'IOT Fogging System Fog Generator. Inbuilt multi-communication channel GSM & 4G',
    warranty: '1',
    endUserPrice: 97564,
    mrp: 115126,
    imagePath: 'assets/product/foggshield_image_1.png',
    coverage: '4,590 ft³',
    category: 'PRO',
  ),
  const Product(
    sNo: '6',
    model: 'SEC FSG1B MG4',
    name: 'FogSHIELD Pro 7000 ft³ (4G)',
    description: 'IOT Fogging System Fog Generator. Inbuilt multi-communication channel GSM & 4G',
    warranty: '1',
    endUserPrice: 116667,
    mrp: 137667,
    imagePath: 'assets/product/foggshield_image_1.png',
    coverage: '7,000 ft³',
    category: 'PRO',
  ),
  const Product(
    sNo: '7',
    model: 'SEC FSG1E MG4',
    name: 'FogSHIELD Pro 17500 ft³ (4G)',
    description: 'IOT Fogging System Fog Generator. Inbuilt multi-communication channel GSM & 4G',
    warranty: '1',
    endUserPrice: 162436,
    mrp: 191674,
    imagePath: 'assets/product/foggshield_image_1.png',
    coverage: '17,500 ft³',
    category: 'PRO',
  ),
  const Product(
    sNo: '8',
    model: 'SEC FSG1H MG4',
    name: 'FogSHIELD Pro 28000 ft³ (4G)',
    description: 'IOT Fogging System Fog Generator. Inbuilt multi-communication channel GSM & 4G',
    warranty: '1',
    endUserPrice: 188462,
    mrp: 222385,
    imagePath: 'assets/product/foggshield_image_1.png',
    coverage: '28,000 ft³',
    category: 'PRO',
  ),

  // --- FLUID BAGS ---
  const Product(
    sNo: '9',
    model: 'SEC FSL1 50FG',
    name: 'Fluid Bag Food Grade 500ml',
    description: 'Compatible with FSG1A and FSG1B series',
    warranty: '1',
    endUserPrice: 9750,
    mrp: 11505,
    imagePath: 'assets/product/foggshield_image_2.png',
    coverage: '500ml',
    category: 'FLUID',
  ),
  const Product(
    sNo: '10',
    model: 'SEC FSL1 75FG',
    name: 'Fluid Bag Food Grade 750ml',
    description: 'Compatible with FSG1E models',
    warranty: '1',
    endUserPrice: 11750,
    mrp: 13865,
    imagePath: 'assets/product/foggshield_image_2.png',
    coverage: '750ml',
    category: 'FLUID',
  ),
  const Product(
    sNo: '11',
    model: 'SEC FSL1 100FG',
    name: 'Fluid Bag Food Grade 1000ml',
    description: 'Compatible with FSG1H models',
    warranty: '1',
    endUserPrice: 13950,
    mrp: 16461,
    imagePath: 'assets/product/foggshield_image_2.png',
    coverage: '1000ml',
    category: 'FLUID',
  ),

  // --- ACCESSORIES ---
  const Product(
    sNo: '12',
    model: 'SEC FSA G1WM1',
    name: 'Wall Mount Stand',
    description: 'Wall mount for FSG1 series Fog Generators',
    warranty: '-',
    endUserPrice: 1900,
    mrp: 2242,
    imagePath: 'assets/product/foggshield_image_4.png',
    coverage: 'Accessory',
    category: 'ACCESSORY',
  ),
  const Product(
    sNo: '13',
    model: 'SEC FSA G1TS1',
    name: 'Table Stand',
    description: 'Table stand for FSG1 series Fog Generators',
    warranty: '-',
    endUserPrice: 8000,
    mrp: 9440,
    imagePath: 'assets/product/foggshield_image_4.png',
    coverage: 'Accessory',
    category: 'ACCESSORY',
  ),
  const Product(
    sNo: '14',
    model: 'SEC FSA BAT1',
    name: '12V 1.2 AH SMF Battery',
    description: 'Used for SEC FSG1A MG4I',
    warranty: '-',
    endUserPrice: 1175,
    mrp: 1386,
    imagePath: 'assets/product/foggshield_image_4.png',
    coverage: 'Battery',
    category: 'ACCESSORY',
  ),
  const Product(
    sNo: '15',
    model: 'SEC FSA BAT2',
    name: '12V 2AH SMF Battery',
    description: 'Standard 12V 2AH Battery',
    warranty: '-',
    endUserPrice: 1350,
    mrp: 1593,
    imagePath: 'assets/product/foggshield_image_4.png',
    coverage: 'Battery',
    category: 'ACCESSORY',
  ),
  const Product(
    sNo: '16',
    model: 'SEC AVR',
    name: 'Automatic Voltage Regulator',
    description: 'Protects fog generator from voltage fluctuations',
    warranty: '-',
    endUserPrice: 3800,
    mrp: 4484,
    imagePath: 'assets/product/foggshield_image_4.png',
    coverage: 'AVR',
    category: 'ACCESSORY',
  ),

  // --- FOGSHIELD NEXUS SERIES ---
  const Product(
    sNo: '17',
    model: 'SEC FSAG1A MG4I',
    name: 'FogSHIELD Nexus 4590 ft³ (IP)',
    description: 'IOT Fog generator and intrusion alarm system. IP, 4G, SMS & Voice call alerts',
    warranty: '1',
    endUserPrice: 107179,
    mrp: 126472,
    imagePath: 'assets/product/foggshield_image_3.png',
    coverage: '4,590 ft³',
    category: 'NEXUS',
  ),
  const Product(
    sNo: '18',
    model: 'SEC FSAG1B MG4I',
    name: 'FogSHIELD Nexus 7000 ft³ (IP)',
    description: 'IOT Fog generator and intrusion alarm system. IP, 4G, SMS & Voice call alerts',
    warranty: '1',
    endUserPrice: 126282,
    mrp: 149013,
    imagePath: 'assets/product/foggshield_image_3.png',
    coverage: '7,000 ft³',
    category: 'NEXUS',
  ),
  const Product(
    sNo: '19',
    model: 'SEC FSAG1A MG4',
    name: 'FogSHIELD Nexus 4590 ft³ (Lite)',
    description: 'IOT Fog generator and intrusion alarm system. 4G, SMS & Voice call alerts',
    warranty: '1',
    endUserPrice: 103974,
    mrp: 122690,
    imagePath: 'assets/product/foggshield_image_3.png',
    coverage: '4,590 ft³',
    category: 'NEXUS',
  ),
  const Product(
    sNo: '20',
    model: 'SEC FSAG1B MG4',
    name: 'FogSHIELD Nexus 7000 ft³ (Lite)',
    description: 'IOT Fog generator and intrusion alarm system. 4G, SMS & Voice call alerts',
    warranty: '1',
    endUserPrice: 123077,
    mrp: 145231,
    imagePath: 'assets/product/foggshield_image_3.png',
    coverage: '7,000 ft³',
    category: 'NEXUS',
  ),

  // --- NEXUS SPECIFIC ACCESSORIES ---
  const Product(
    sNo: '21',
    model: 'SEC FSL1 50FG (N)',
    name: 'Fluid Bag Food Grade (Nexus)',
    description: 'Compatible with FSAG1A MG4I & FSAG1B MG4I',
    warranty: '-',
    endUserPrice: 9750,
    mrp: 11505,
    imagePath: 'assets/product/foggshield_image_2.png',
    coverage: '500ml',
    category: 'FLUID',
  ),
  const Product(
    sNo: '24',
    model: 'SEC FSA BAT1 (2AH)',
    name: '12V 2AH Battery (Nexus)',
    description: 'High capacity battery for Nexus models',
    warranty: '-',
    endUserPrice: 1075,
    mrp: 1269,
    imagePath: 'assets/product/foggshield_image_4.png',
    coverage: 'Battery',
    category: 'ACCESSORY',
  ),

  // --- SOFTWARE & SERVICES ---
  const Product(
    sNo: '25',
    model: 'SFN AFMS',
    name: 'AFMS Software License',
    description: 'Web-based alarm monitoring software. Real-time status for IP based panels',
    warranty: '-',
    endUserPrice: 3000,
    mrp: 3540,
    imagePath: 'assets/product/foggshield_image_4.png',
    coverage: 'Software',
    category: 'SOFTWARE',
  ),
  const Product(
    sNo: '26',
    model: 'SVC MONITOR',
    name: 'Alarm Monitoring Service',
    description: 'Monitoring charges per fogging system per month (Min 12 months)',
    warranty: '-',
    endUserPrice: 1000,
    mrp: 1180,
    imagePath: 'assets/product/foggshield_image_4.png',
    coverage: 'Service',
    category: 'SERVICE',
  ),
];